# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.srcs/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/Task2_Design_FourBitAdder_0_0.xci
# IP: The module: 'Task2_Design_FourBitAdder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_OneBitAdder_0_0/FourBitAdder_OneBitAdder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_OneBitAdder_0_0 || ORIG_REF_NAME==FourBitAdder_OneBitAdder_0_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_OneBitAdder_0_1/FourBitAdder_OneBitAdder_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_OneBitAdder_0_1 || ORIG_REF_NAME==FourBitAdder_OneBitAdder_0_1} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_OneBitAdder_0_2/FourBitAdder_OneBitAdder_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_OneBitAdder_0_2 || ORIG_REF_NAME==FourBitAdder_OneBitAdder_0_2} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_OneBitAdder_0_3/FourBitAdder_OneBitAdder_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_OneBitAdder_0_3 || ORIG_REF_NAME==FourBitAdder_OneBitAdder_0_3} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_0/FourBitAdder_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_0 || ORIG_REF_NAME==FourBitAdder_xlslice_0_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlconcat_0_0/FourBitAdder_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlconcat_0_0 || ORIG_REF_NAME==FourBitAdder_xlconcat_0_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_1/FourBitAdder_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_1 || ORIG_REF_NAME==FourBitAdder_xlslice_0_1} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_2/FourBitAdder_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_2 || ORIG_REF_NAME==FourBitAdder_xlslice_0_2} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_3/FourBitAdder_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_3 || ORIG_REF_NAME==FourBitAdder_xlslice_0_3} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_4/FourBitAdder_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_4 || ORIG_REF_NAME==FourBitAdder_xlslice_0_4} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_1_0/FourBitAdder_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_1_0 || ORIG_REF_NAME==FourBitAdder_xlslice_1_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_2_0/FourBitAdder_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_2_0 || ORIG_REF_NAME==FourBitAdder_xlslice_2_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_3_0/FourBitAdder_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_3_0 || ORIG_REF_NAME==FourBitAdder_xlslice_3_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlconstant_0_0/FourBitAdder_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlconstant_0_0 || ORIG_REF_NAME==FourBitAdder_xlconstant_0_0} -quiet] -quiet

# XDC: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task2_Design_FourBitAdder_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.srcs/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/Task2_Design_FourBitAdder_0_0.xci
# IP: The module: 'Task2_Design_FourBitAdder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_OneBitAdder_0_0/FourBitAdder_OneBitAdder_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_OneBitAdder_0_0 || ORIG_REF_NAME==FourBitAdder_OneBitAdder_0_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_OneBitAdder_0_1/FourBitAdder_OneBitAdder_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_OneBitAdder_0_1 || ORIG_REF_NAME==FourBitAdder_OneBitAdder_0_1} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_OneBitAdder_0_2/FourBitAdder_OneBitAdder_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_OneBitAdder_0_2 || ORIG_REF_NAME==FourBitAdder_OneBitAdder_0_2} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_OneBitAdder_0_3/FourBitAdder_OneBitAdder_0_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_OneBitAdder_0_3 || ORIG_REF_NAME==FourBitAdder_OneBitAdder_0_3} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_0/FourBitAdder_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_0 || ORIG_REF_NAME==FourBitAdder_xlslice_0_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlconcat_0_0/FourBitAdder_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlconcat_0_0 || ORIG_REF_NAME==FourBitAdder_xlconcat_0_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_1/FourBitAdder_xlslice_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_1 || ORIG_REF_NAME==FourBitAdder_xlslice_0_1} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_2/FourBitAdder_xlslice_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_2 || ORIG_REF_NAME==FourBitAdder_xlslice_0_2} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_3/FourBitAdder_xlslice_0_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_3 || ORIG_REF_NAME==FourBitAdder_xlslice_0_3} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_0_4/FourBitAdder_xlslice_0_4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_0_4 || ORIG_REF_NAME==FourBitAdder_xlslice_0_4} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_1_0/FourBitAdder_xlslice_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_1_0 || ORIG_REF_NAME==FourBitAdder_xlslice_1_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_2_0/FourBitAdder_xlslice_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_2_0 || ORIG_REF_NAME==FourBitAdder_xlslice_2_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlslice_3_0/FourBitAdder_xlslice_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlslice_3_0 || ORIG_REF_NAME==FourBitAdder_xlslice_3_0} -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_xlconstant_0_0/FourBitAdder_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FourBitAdder_xlconstant_0_0 || ORIG_REF_NAME==FourBitAdder_xlconstant_0_0} -quiet] -quiet

# XDC: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/src/FourBitAdder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task2_Design_FourBitAdder_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
