# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kapug/try_5_hello_world/try_5_hello_world.srcs/sources_1/bd/try_5_at/ip/try_5_at_axi_gpio_0_0/try_5_at_axi_gpio_0_0.xci
# IP: The module: 'try_5_at_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/bd/try_5_at/ip/try_5_at_axi_gpio_0_0/try_5_at_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'try_5_at_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/bd/try_5_at/ip/try_5_at_axi_gpio_0_0/try_5_at_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'try_5_at_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/bd/try_5_at/ip/try_5_at_axi_gpio_0_0/try_5_at_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'try_5_at_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/kapug/try_5_hello_world/try_5_hello_world.srcs/sources_1/bd/try_5_at/ip/try_5_at_axi_gpio_0_0/try_5_at_axi_gpio_0_0.xci
# IP: The module: 'try_5_at_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/bd/try_5_at/ip/try_5_at_axi_gpio_0_0/try_5_at_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'try_5_at_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/bd/try_5_at/ip/try_5_at_axi_gpio_0_0/try_5_at_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'try_5_at_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/bd/try_5_at/ip/try_5_at_axi_gpio_0_0/try_5_at_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'try_5_at_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
