# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Kashif/Desktop/WS2024/EMP 2/LAB/PROJECT/Microblaze.srcs/sources_1/bd/design_microblaze/ip/design_microblaze_dlmb_v10_0/design_microblaze_dlmb_v10_0.xci
# IP: The module: 'design_microblaze_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kashif/Desktop/WS2024/EMP 2/LAB/PROJECT/Microblaze.gen/sources_1/bd/design_microblaze/ip/design_microblaze_dlmb_v10_0/design_microblaze_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Kashif/Desktop/WS2024/EMP 2/LAB/PROJECT/Microblaze.srcs/sources_1/bd/design_microblaze/ip/design_microblaze_dlmb_v10_0/design_microblaze_dlmb_v10_0.xci
# IP: The module: 'design_microblaze_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kashif/Desktop/WS2024/EMP 2/LAB/PROJECT/Microblaze.gen/sources_1/bd/design_microblaze/ip/design_microblaze_dlmb_v10_0/design_microblaze_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_microblaze_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
