# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.srcs/sources_1/bd/Task2_Design/ip/Task2_Design_clk_wiz_0/Task2_Design_clk_wiz_0.xci
# IP: The module: 'Task2_Design_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_clk_wiz_0/Task2_Design_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task2_Design_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_clk_wiz_0/Task2_Design_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task2_Design_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_clk_wiz_0/Task2_Design_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task2_Design_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.srcs/sources_1/bd/Task2_Design/ip/Task2_Design_clk_wiz_0/Task2_Design_clk_wiz_0.xci
# IP: The module: 'Task2_Design_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_clk_wiz_0/Task2_Design_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task2_Design_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_clk_wiz_0/Task2_Design_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task2_Design_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/ip/Task2_Design_clk_wiz_0/Task2_Design_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Task2_Design_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
