domain_path: C:\Users\kapug\try_5_hello_world\Blutooth_action\export\Blutooth_action\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
