#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_IIC_0 */
#define XPAR_AXI_IIC_0_COMPATIBLE xlnx,axi-iic-2.1
#define XPAR_AXI_IIC_0_BASEADDR 0x40800000
#define XPAR_AXI_IIC_0_HIGHADDR 0x4080ffff
#define XPAR_AXI_IIC_0_HAS10BITADDR 0x0
#define XPAR_AXI_IIC_0_GPOUTWIDTH 0x0

/* Canonical definitions for peripheral AXI_IIC_0 */
#define XPAR_XIIC_0_BASEADDR 0x40800000
#define XPAR_XIIC_0_GPOUTWIDTH 0x0
#define XPAR_XIIC_0_HIGHADDR 0x4080ffff
#define XPAR_XIIC_0_HAS10BITADDR 0x0
#define XPAR_XIIC_0_COMPATIBLE xlnx,axi-iic-2.1

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE xlnx,axi-uartlite-2.0
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x2580
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x2580
#define XPAR_XUARTLITE_0_COMPATIBLE xlnx,axi-uartlite-2.0
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral PMODBLE_0 */
#define XPAR_PMODBLE_0_BASEADDR 0x44a00000
#define XPAR_PMODBLE_0_HIGHADDR 0x44a0ffff

/*  BOARD definition */
#define XPS_BOARD_NEXYS-A7-100T

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x20000
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

#define STDOUT_BASEADDRESS 0x40600000
#define STDIN_BASEADDRESS 0x40600000

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */