# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kapug/try_5_hello_world/try_5_hello_world.srcs/sources_1/ip/AXI_DPTI_0/AXI_DPTI_0.xci
# IP: The module: 'AXI_DPTI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/fifo_generator_dpti/fifo_generator_dpti.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_dpti || ORIG_REF_NAME==fifo_generator_dpti} -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/fifo_generator_dpti/fifo_generator_dpti.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_dpti || ORIG_REF_NAME==fifo_generator_dpti} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/fifo_generator_dpti/fifo_generator_dpti_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_dpti || ORIG_REF_NAME==fifo_generator_dpti} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/AXI_DPTI_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DPTI_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/timing.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DPTI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/kapug/try_5_hello_world/try_5_hello_world.srcs/sources_1/ip/AXI_DPTI_0/AXI_DPTI_0.xci
# IP: The module: 'AXI_DPTI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/fifo_generator_dpti/fifo_generator_dpti.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_dpti || ORIG_REF_NAME==fifo_generator_dpti} -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/fifo_generator_dpti/fifo_generator_dpti.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_dpti || ORIG_REF_NAME==fifo_generator_dpti} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/fifo_generator_dpti/fifo_generator_dpti_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_dpti || ORIG_REF_NAME==fifo_generator_dpti} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/AXI_DPTI_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DPTI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/ip/AXI_DPTI_0/src/timing.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DPTI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
