# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/spi.xdc

# Block Designs: bd/try_5_at/try_5_at.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at || ORIG_REF_NAME==try_5_at} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_microblaze_0_2/try_5_at_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_microblaze_0_2 || ORIG_REF_NAME==try_5_at_microblaze_0_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_axi_uartlite_0_2/try_5_at_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_axi_uartlite_0_2 || ORIG_REF_NAME==try_5_at_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_dlmb_v10_2/try_5_at_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_dlmb_v10_2 || ORIG_REF_NAME==try_5_at_dlmb_v10_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_ilmb_v10_2/try_5_at_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_ilmb_v10_2 || ORIG_REF_NAME==try_5_at_ilmb_v10_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_dlmb_bram_if_cntlr_2/try_5_at_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==try_5_at_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_ilmb_bram_if_cntlr_2/try_5_at_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==try_5_at_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_lmb_bram_2/try_5_at_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_lmb_bram_2 || ORIG_REF_NAME==try_5_at_lmb_bram_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_xbar_2/try_5_at_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_xbar_2 || ORIG_REF_NAME==try_5_at_xbar_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_microblaze_0_axi_periph_2/try_5_at_microblaze_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_microblaze_0_axi_periph_2 || ORIG_REF_NAME==try_5_at_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_microblaze_0_axi_intc_1/try_5_at_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_microblaze_0_axi_intc_1 || ORIG_REF_NAME==try_5_at_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_microblaze_0_xlconcat_1/try_5_at_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_microblaze_0_xlconcat_1 || ORIG_REF_NAME==try_5_at_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_mdm_1_2/try_5_at_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_mdm_1_2 || ORIG_REF_NAME==try_5_at_mdm_1_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_clk_wiz_1_2/try_5_at_clk_wiz_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_clk_wiz_1_2 || ORIG_REF_NAME==try_5_at_clk_wiz_1_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_rst_clk_wiz_1_100M_2/try_5_at_rst_clk_wiz_1_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==try_5_at_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/try_5_at/ip/try_5_at_axi_gpio_0_0/try_5_at_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==try_5_at_axi_gpio_0_0 || ORIG_REF_NAME==try_5_at_axi_gpio_0_0} -quiet] -quiet

# XDC: c:/Users/kapug/try_5_hello_world/try_5_hello_world.gen/sources_1/bd/try_5_at/try_5_at_ooc.xdc
