domain_path: C:\Users\Kashif\Desktop\VITIS01\platform\export\platform\sw\standalone_microblaze_0
app_src_dir: D:\XILINX\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
