# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/FullAdder/Task2_BCD_Segments/Nexys-A7-100T-Master.xdc

# Block Designs: bd/Task2_Design/Task2_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task2_Design || ORIG_REF_NAME==Task2_Design} -quiet] -quiet

# IP: bd/Task2_Design/ip/Task2_Design_FourBitAdder_0_0/Task2_Design_FourBitAdder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task2_Design_FourBitAdder_0_0 || ORIG_REF_NAME==Task2_Design_FourBitAdder_0_0} -quiet] -quiet

# IP: bd/Task2_Design/ip/Task2_Design_BCD_5in_8out_0_0/Task2_Design_BCD_5in_8out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task2_Design_BCD_5in_8out_0_0 || ORIG_REF_NAME==Task2_Design_BCD_5in_8out_0_0} -quiet] -quiet

# IP: bd/Task2_Design/ip/Task2_Design_SegControl_0_0/Task2_Design_SegControl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task2_Design_SegControl_0_0 || ORIG_REF_NAME==Task2_Design_SegControl_0_0} -quiet] -quiet

# IP: bd/Task2_Design/ip/Task2_Design_xlslice_0_0/Task2_Design_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task2_Design_xlslice_0_0 || ORIG_REF_NAME==Task2_Design_xlslice_0_0} -quiet] -quiet

# IP: bd/Task2_Design/ip/Task2_Design_xlslice_1_0/Task2_Design_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task2_Design_xlslice_1_0 || ORIG_REF_NAME==Task2_Design_xlslice_1_0} -quiet] -quiet

# IP: bd/Task2_Design/ip/Task2_Design_Switching_Control_0_0/Task2_Design_Switching_Control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task2_Design_Switching_Control_0_0 || ORIG_REF_NAME==Task2_Design_Switching_Control_0_0} -quiet] -quiet

# IP: bd/Task2_Design/ip/Task2_Design_clk_wiz_0/Task2_Design_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task2_Design_clk_wiz_0 || ORIG_REF_NAME==Task2_Design_clk_wiz_0} -quiet] -quiet

# IP: bd/Task2_Design/ip/Task2_Design_reset_inv_0_0/Task2_Design_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Task2_Design_reset_inv_0_0 || ORIG_REF_NAME==Task2_Design_reset_inv_0_0} -quiet] -quiet

# XDC: c:/FullAdder/Task2_BCD_Segments/Task2_BCD_Segments.gen/sources_1/bd/Task2_Design/Task2_Design_ooc.xdc
